spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public

# Настройки JWT
jwt:
  secret: ${JWT_SECRET:6701bcea-351a-4a1b-992b-9bc57618cae8}
  expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    ru.school.tournamenthub: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs